#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          TweedleDee,    tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          TweedleDum,    tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          TweedleDumber, tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     driveL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     driveR,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     flagTurn,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     reel,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    clamp,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_2,    position,             tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


task main()
{
	getJoystickSettings (joystick);

	waitForStart();   // wait for start of tele-op phase

	while (true)
	{
		float onex = joystick.joy1_x1; //Values set equal to the position of the joystick
		float oney = joystick.joy1_y1;
		float twox = joystick.joy1_x2;
		float twoy = joystick.joy1_y2;

		if(abs(onex)<16)onex=0;

		if(abs(oney)<16)oney=0;
		//Helps prevent the robot from moving by the joysticks getting stuck
		if(abs(twox)<16)twox=0;

		if(abs(twoy)<16)twoy=0;

		int left; //Variables will go to robot after they're established
		int right;

		//int turn = 1;

		//int power = 90;

		//int position;

		float  divide;
		float  mult;
		mult = 1;
		divide = 2;
		//left = oney/divide; //Establishes the values that the robot will recieve for movement
		left = oney*mult;
		//right = oney/divide;
		right = oney*mult;

		//left+= twox/(divide);
		//right-=twox/(divide);
		left += twox*mult;
		right -= twox*mult;

		//left = oney;
		//right = twoy;

		motor[driveL]=left; //Gives the motors their values
		motor[driveR]=right;

		//motor[driveL]=oney;
		//motor[driveR]=twoy;

		if (joy1Btn(1))
		{
			motor[flagTurn]=20; //Motor value of flag turning device
			wait1Msec(10);
		}
		else if (joy1Btn(2))
		{
			motor[flagTurn]=-100; //Flag turn in other direction
			wait1Msec(10);
		}
		else
		{
			motor[flagTurn]=0;
		}
		if (joy1Btn(8))
		{
			motor[reel]=255;
			wait1Msec(10);
		}
		else if (joy1Btn(6))
		{
			motor[reel]=-25;
			wait1Msec(10);
		}
		else
		{
			motor[reel]=15;
		}
		/*while (joy1Btn(5))
		{
		servo[clamp]=position;
		wait1Msec(1);
		position++;
		}
		while (joy1Btn(7))
		{
		servo[clamp]=position;
		wait1Msec(1);
		position--;
		}*/
		/*if (joy1Btn(5))
		{
		if (turn == 1)
		{
		//servo[clamp]=50;
		position = 50;
		turn = 2;
		}
		else if (turn == 2)
		{
		//servo[clamp]=120;
		position = 120;
		turn = 1;
		}
		servo[clamp] = position;
		wait1Msec(10);
		}*/
		if (joy1Btn(5))
		{
			servo[clamp]=90;
			//power = 110;
			//wait1Msec(10);
		}
		else if (joy1Btn(7))
		{
			servo[clamp]=0;
			//power = 90;
			//wait1Msec(10);
		}
		/*else
		{
		servo[positioner]=0;
		}*/
		if (joy1Btn(3))
		{
			motor[lift]=50;
			wait10Msec(1);
		}
		else if (joy1Btn(4))
		{
			motor[lift]=-50;
			wait10Msec(1);
		}
	}
}
