#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     ear1,           sensorSoundDB)
#pragma config(Sensor, S3,     ear2,           sensorSoundDB)
#pragma config(Motor,  motorA,          bitch,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     driveL1,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     driveR1,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     driveL2,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     driveR2,       tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    thing,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int speed=50;
	ClearTimer(T1);
  while (true)
  {
  	int avgpt1=SensorValue[ear1]+SensorValue[ear2];
  	int avgpt2=avgpt1/2;
  	float avgpt3=avgpt2*1.5;
  	motor[bitch]=100;
		wait1Msec(1);
 		motor[driveL1]=speed;
 		motor[driveR1]=speed;
 		motor[driveL2]=speed;
 		motor[driveR2]=speed;
 		servo[thing]=0;
 		wait10Msec(25);
 		motor[driveL1]=-speed;
 		motor[driveR1]=-speed;
 		motor[driveL2]=-speed;
 		motor[driveR2]=-speed;
 		servo[thing]=100;
 		wait10Msec(25);
  }
}
