#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     failSafe,       sensorI2CHiTechnicColor)
#pragma config(Sensor, S3,     multiplexor,    sensorHiTechnicTouchMux)
#pragma config(Motor,  mtr_S1_C1_1,     driveL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     driveR,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     flagTurn,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     lock,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    preLoad,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    bucket,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "AdvancedSensors.c"
#include "drivers/hitechnic-sensormux.h"

task robotDrive()
{
	while (true)
	{
		servo[preLoad]=245;

		float onex = joystick.joy1_x1;
		float oney = joystick.joy1_y1;
		float twox = joystick.joy1_x2;
		float twoy = joystick.joy1_y2;

		if(abs(onex)<16)onex=0;

		if(abs(oney)<16)oney=0;
		//Helps prevent the robot from moving by the joysticks getting stuck
		if(abs(twox)<16)twox=0;

		if(abs(twoy)<16)twoy=0;

		int left; //Variables will go to robot after they're established
		int right;

		float  divide;
		float  mult;
		mult = 2;
		divide = 2;
		//left = oney/divide; //Establishes the values that the robot will recieve for movement
		left = oney;
		//right = oney/divide;
		right = oney;

		left+= twox/(divide);
		right-=twox/(divide);
		//left += twox*mult;
		//right -= twox*mult;

		//left = oney;
		//right = twoy;

		motor[driveL]=left; //Gives the motors their values
		motor[driveR]=right;

		//motor[driveL]=oney;
		////motor[driveR]=twoy;

		abortTimeslice();
	}
}
task turningTheFlag()
{
	while (true)
	{
		if (joy1Btn(1))
		{
			motor[flagTurn]=20; //Motor value of flag turning device
			wait1Msec(10);
		}
		else if (joy1Btn(2))
		{
			motor[flagTurn]=-255; //Flag turn in other direction
			wait1Msec(10);
		}
		else if (joy2Btn(8))
		{
			motor[flagTurn]=10;
		}
		else if (joy2Btn(7))
		{
			motor[flagTurn]=-10;
		}
		else
		{
			motor[flagTurn]=0;
		}
		abortTimeslice();
	}
}
task blockGrip()
{
	while (true)
	{
		if (joy1Btn(7))
		{
			servo[bucket]=200;
		}
		else if (joy1Btn(5))
		{
			servo[bucket]=115;
		}
		else if (joy1Btn(9))
		{
			servo[bucket]=0;
		}
		abortTimeslice();
	}
}
task pullUp()
{
	while (true)
	{
		int red=0;
		int blue=0;
		int green=0;

		getRGB(failSafe, red, green, blue);
		nxtDisplayTextLine(3, "Red:    %d",  red);
		nxtDisplayTextLine(4, "Green:  %d",  green);
		nxtDisplayTextLine(5, "Blue:   %d",  blue);

		if (joy1Btn(10))
		{
			while(green > 200||green < 100)
			{
				servo[bucket]=120;
				motor[lift]=-255;
				getRGB(failSafe, red, green, blue);
				wait10Msec(1);
			}
			motor[lift]=0;
		}

		if (joy1Btn(8))
		{
			if (green < 150&&green > 100)
			{
				motor[lift]=0;
				wait10Msec(1);
			}
			else
			{
				motor[lift]=-255;
				wait10Msec(1);
			}
		}
		else if (joy1Btn(6))
		{
			if (green < 100)
			{
				motor[lift]=0;
				wait10Msec(1);
			}
			else
			{
				motor[lift]=255;
				wait10Msec(1);
			}
		}
		else
		{
			motor[lift]=0;
		}
		abortTimeslice();
	}
}
task lockHook()
{
	while(true)
	{
		if (SensorValue[multiplexor]==2||SensorValue[multiplexor]==6)
		{
			motor[lock]=0;
		}
		else if (joy1Btn(4))
		{
			motor[lock]=10;
		}
		else if (joy1Btn(3))
		{
			motor[lock]=-10;
		}
		else if (joy2Btn(1))
		{
			motor[lock]=15;
		}
		else if (joy2Btn(2))
		{
			motor[lock]=-15;
		}
		else if (joy2Btn(4))
		{
			motor[lock]=150;
		}
		else if (joy2Btn(3))
		{
			motor[lock]=-150;
		}
		else
		{
			motor[lock]=0;
		}
		abortTimeslice();
	}
}
task slowMove()
{
	while(true)
	{
		int slow=50;
		while(joystick.joy1_TopHat==0)
		{
			motor[driveL]=slow;
			motor[driveR]=slow;
			wait1Msec(1);
		}
		while(joystick.joy1_TopHat==2)
		{
			motor[driveL]=slow;
			motor[driveR]=-slow;
			wait1Msec(1);
		}
		 while(joystick.joy1_TopHat==4)
		{
			motor[driveL]=-slow;
			motor[driveR]=-slow;
			wait1Msec(1);
		}
		 while(joystick.joy1_TopHat==6)
		{
			motor[driveL]=-slow;
			motor[driveR]=slow;
			wait1Msec(1);
		}
		abortTimeslice();
	}
}

task main()
{
	getJoystickSettings (joystick);

	waitForStart(); // wait for start of tele-op phase

	StartTask(robotDrive);
	StartTask(slowMove);
	StartTask(turningTheFlag);
	StartTask(blockGrip);
	StartTask(pullUp);
	StartTask(lockHook);

	while (true)
	{
		wait1Msec(1);
	}
}
