#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     driveL1,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     driveR1,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     driveL2,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     driveR2,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"

task main()
{
  waitForStart();   // wait for start of tele-op phase

  getJoystickSettings (joystick);

  while (true)
  {
	  float onex = joystick.joy1_x1; //Values set equal to the position of the joystick
		float oney = joystick.joy1_y1;
		float twox = joystick.joy1_x2;
		float twoy = joystick.joy1_y2;

		motor[driveL1]=oney;
		motor[driveR1]=oney;
		motor[driveL2]=oney;
		motor[driveR2]=oney;
  }
}
