#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     liftheight,     sensorI2CHiTechnicColor)
#pragma config(Sensor, S3,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     driveR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     driveL,        tmotorTetrix, openLoop, revesed)
#pragma config(Servo,  srvo_S1_C3_1,    binlift,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    glowstick1,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_3,    glowstick2,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_4,    centerpiece,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    linesensor,           tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "AdvancedSensors.c"

task main ()
{
	/*
  int nRed;
  int nGreen;
  int nBlue;
  */

  const tSensors kColorSensorPort   = S2;
  SensorType[kColorSensorPort] = sensorI2CHiTechnicColor;

  ClearTimer(T1);

	motor[arm] = 80;

	wait10Msec(100);





	while(time1[T1] < 12500){
		/*getRGB(kColorSensorPort, nRed, nGreen, nBlue);
		nxtDisplayTextLine(2, "Color:  %d",  (short) SensorValue[kColorSensorPort]);
			  nxtDisplayTextLine(3, "Red:    %d",  nRed);
			  nxtDisplayTextLine(4, "Green:  %d",  nGreen);
			  nxtDisplayTextLine(5, "Blue:   %d",  nBlue);
*/
	  motor[arm] = 80;
	  motor[driveL] = 100;
	  motor[driveR] = 100;
		wait10Msec(50);

		motor[arm] = -50;
		motor[driveL] = -100;
		motor[driveR] = -100;
		wait10Msec(50);


	}
	motor[arm] = 0;

  while(time1[T1] < 30000)
  {
  	motor[arm] = 80;
		wait10Msec(50);

		motor[arm] = -50;
		wait10Msec(50);
  	if(random(1) == 0){
	  	motor[driveL] = random(100);
	  	motor[driveR] = -random(100);
  	}
  	else{
  		motor[driveL] = -random(100);
	  	motor[driveR] = random(100);
  	}
  	wait10Msec(random(25));
	}



}

/*
* $Id: hitechnic-irseeker-v2-test1.c 109 2012-09-25 17:10:26Z xander $
*/
