#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     Seeker,         sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     Gryo,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     driveFL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     driveFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     driveBL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     driveBR,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "drivers/hitechnic-irseeker-v2.h"

task main()
{
	int speed=100;

	int acS1, acS2, acS3, acS4, acS5 = 0;

	bool go=true;

  waitForStart();

  ClearTimer(T1);

  while (T1<=2000)
  {
		motor[driveFL]=-speed;
		motor[driveFR]=-speed;
		motor[driveBL]=-speed;
		motor[driveBR]=-speed;
	}
	while (T1>=2000&&T1<=4000)
		motor[driveFL]=speed;
		motor[driveFR]=-speed;
		motor[driveBL]=-speed;
		motor[driveBR]=speed;
		wait1Msec(2000);
		motor[driveFL]=speed;
		motor[driveFR]=speed;
		motor[driveBL]=speed;
		motor[driveBR]=speed;
		wait1Msec(1500);
  }
  motor[driveFL]=0;
  motor[driveFR]=0;
  motor[driveBL]=0;
  motor[driveBR]=0;
}
