#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     Seeker,         sensorI2CCustom)
#pragma config(Sensor, S3,     Gryo,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     driveFL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     driveFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     driveBL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     driveBR,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "drivers/hitechnic-irseeker-v2.h"
#include "drivers/hitechnic-touchmux.h"

int speed=100;

int acS1, acS2, acS3, acS4, acS5 = 0;

task IRSweep3
{
	ClearTimer(T1);
	while(time1[T1]<4000)
	{
		motor[driveFL]=-speed;
		motor[driveFR]=speed;
		motor[driveBL]=speed;
		motor[driveBR]=-speed;
		/*HTIRS2readAllACStrength(Seeker, acS1, acS2, acS3, acS4, acS5);
		if((acS4-acS3)<40&&(acS4+acS3)>60)
		{
			PlaySound(soundBeepBeep);
			motor[driveFL]=-speed;
			motor[driveFR]=-speed;
			motor[driveBL]=-speed;
			motor[driveBR]=-speed;
			wait1Msec(500);
			motor[driveFL]=-speed;
			motor[driveFR]=speed;
			motor[driveBL]=speed;
			motor[driveBR]=-speed;
			wait1Msec(4000);
		}*/
	}
	StopAllTasks();
}
task IRSweep2
{
	ClearTimer(T1);
	while(time1[T1]<1500)
	{
		motor[driveFL]=speed/2;
		motor[driveFR]=-speed/2;
		motor[driveBL]=-speed/2;
		motor[driveBR]=speed/2;
	  HTIRS2readAllACStrength(Seeker, acS1, acS2, acS3, acS4, acS5);
	  if((acS4-acS3)<60&&(acS4+acS3)>40)
	  {
	  	PlaySound(soundBeepBeep);
	  	motor[driveFL]=-speed;
	  	motor[driveFR]=speed;
	  	motor[driveBL]=speed;
	  	motor[driveBR]=-speed;
	  	wait1Msec(800);
	  	motor[driveFL]=-speed;
	  	motor[driveFR]=speed;
	  	motor[driveBL]=-speed;
	  	motor[driveBR]=speed;
	  	wait1Msec(400);
	  	motor[driveFL]=-speed;
	  	motor[driveFR]=speed;
	  	motor[driveBL]=speed;
	  	motor[driveBR]=-speed;
	  	wait1Msec(3750);
	  	motor[driveFL]=speed;
	  	motor[driveFR]=-speed;
	  	motor[driveBL]=-speed;
	  	motor[driveBR]=speed;
	  	wait1Msec(1000);
	  	motor[driveFL]=-speed;
	  	motor[driveFR]=speed;
	  	motor[driveBL]=speed;
	  	motor[driveBR]=-speed;
	  	wait1Msec(2000);
	  	StopAllTasks();
	  }
	}
	motor[driveFL]=-speed/2;
	motor[driveFR]=-speed/2;
	motor[driveBL]=-speed/2;
	motor[driveBR]=-speed/2;
	wait1Msec(500);
	StartTask(IRSweep3);
}


task IRSweep1
{
	ClearTimer(T1);
	while(time1[T1]<3900)
	{
		motor[driveFL]=speed/2;
		motor[driveFR]=-speed/2;
		motor[driveBL]=-speed/2;
		motor[driveBR]=speed/2;
		HTIRS2readAllACStrength(Seeker, acS1, acS2, acS3, acS4, acS5);
		if((acS4-acS3)<60&&(acS4+acS3)>40&&time1[T1]>1000)
		{
			PlaySound(soundBeepBeep);
			motor[driveFL]=-speed;
			motor[driveFR]=speed;
			motor[driveBL]=speed;
			motor[driveBR]=-speed;
			wait1Msec(1150);
			motor[driveFL]=-speed;
			motor[driveFR]=-speed;
			motor[driveBL]=-speed;
			motor[driveBR]=-speed;
			wait1Msec(3000);
			StopAllTasks();
		}
	}
	motor[driveFL]=-speed/2;
	motor[driveFR]=-speed/2;
	motor[driveBL]=-speed/2;
	motor[driveBR]=-speed/2;
	wait1Msec(400);
	StartTask(IRSweep2);
}
task offRamp()
{
	motor[driveFL]=-speed;
	motor[driveFR]=-speed;
	motor[driveBL]=-speed;
	motor[driveBR]=-speed;
	wait1Msec(2000);
	motor[driveFL]=speed/2;
	motor[driveFR]=-speed/2;
	motor[driveBL]=-speed/2;
	motor[driveBR]=speed/2;
	wait1Msec(1750);
	motor[driveFL]=speed;
	motor[driveFR]=speed;
	motor[driveBL]=speed;
	motor[driveBR]=speed;
	wait1Msec(1500);
	motor[driveFL]=0;
	motor[driveFR]=0;
	motor[driveBL]=0;
	motor[driveBR]=0;
	StartTask(IRSweep1);
}
task main()
{
	waitForStart();
	ClearTimer(T1);
	StartTask(offRamp);
	while(true)
	{
		wait1Msec(1);
	}
}
