#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     BR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     FR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     FL,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     BL,            tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task frontLeft()
{
	while (true)
	{
		if(joy1Btn(7))
		{
			motor[FL]=50;
		}
		else if(joy1Btn(1))
		{
			motor[FL]=-50;
		}
		else
		{
			motor[FL]=0;
		}
		abortTimeslice();
	}
}
task frontRight()
{
	while (true)
	{
		if(joy1Btn(8))
		{
			motor[FR]=50;
		}
		else if(joy1Btn(4))
		{
			motor[FR]=-50;
		}
		else
		{
			motor[FR]=0;
		}
		abortTimeslice();
	}
}
task backLeft()
{
	while (true)
	{
		if(joy1Btn(5))
		{
			motor[BL]=50;
		}
		else if(joy1Btn(2))
		{
			motor[BL]=-50;
		}
		else
		{
			motor[BL]=0;
		}
		abortTimeslice();
	}
}
task backRight()
{
	while (true)
	{
		if(joy1Btn(6))
		{
			motor[BR]=50;
		}
		else if(joy1Btn(3))
		{
			motor[BR]=-50;
		}
		else
		{
			motor[BR]=0;
		}
		abortTimeslice();
	}
}
task main()
{
	getJoystickSettings(joystick);

	waitForStart();

	StartTask(frontLeft);
	StartTask(frontRight);
	StartTask(backLeft);
	StartTask(backRight);

	while(true)
	{
		wait10Msec(1);
	}
}
