#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Motor,  mtr_S1_C1_1,     FR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     BR,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     FL,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     BL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     winch,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     sweeper,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    clamp,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task go(){
    while(true){
			float fl_value = 0;
			float fr_value = 0;
			float bl_value = 0;
			float br_value = 0;
			int up = 170; int down = 215; //clamp servos
			float sweeperValue = 0;


			float yVal = joystick.joy1_y1 * .787 / 4; //scaling function
			float xVal = joystick.joy1_x1 * .787 / 4;
			float xVal2 = joystick.joy1_x2 * .787 / 4;

			int sweep = joystick.joy2_y1;

      if(abs(yVal) > 15){ //forward backward
          fl_value += yVal;
          fr_value += yVal;
          bl_value += yVal;
          br_value += yVal;
      }
			if(abs(joystick.joy1_x1) > 15){//sideways movement
				fl_value += xVal;
				fr_value -= xVal;
				bl_value -= xVal;
				br_value += xVal;
			}
			if(abs(joystick.joy1_x2) > 15){ //pivot
				fl_value += xVal2;
				fr_value -= xVal2;
				bl_value += xVal2;
				br_value -= xVal2;
			}

			if (joy1Btn(5)){
				servo[clamp] = up;
			}
		  if (joy1Btn(7)){
				servo[clamp] = down;
			}

			if (joy1Btn (1) || sweep > 15){
			  sweeperValue = 100;
				}
			else if (joy1Btn (2)|| sweep < -30){
			  sweeperValue = -30;
			}
			else{
			  sweeperValue = 0;
		}

		if (abs(sweeperValue) < 15)
			sweeperValue = 0;

				if (joy1Btn (6) || joy2Btn(6)){
				motor[winch] = 100;
				}
			else if (joy1Btn (8) || joy2Btn(8)){
				motor[winch] = -15;
			}
			else
				motor[winch] = 0;

			motor[FL] = fl_value;
			motor[FR] = fr_value;
			motor[BL] = bl_value;
			motor[BR] = br_value;
			motor[sweeper] = sweeperValue;

      abortTimeslice();
    }
}

task main()
{
    getJoystickSettings(joystick);

    waitForStart();

    StartTask(go);

    while(true)
    {
        wait10Msec(1);
    }
  }
