#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     failSafe,       sensorI2CHiTechnicColor)
#pragma config(Motor,  mtr_S1_C1_1,     driveL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     driveR,        tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_1,     flagTurn,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lift,          tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "AdvancedSensors.c"

task main()
{

  //waitForStart();

	wait1Msec(1000);
  int red=0;
	int blue=0;
	int green=0;

	getRGB(failSafe, red, green, blue);
	nxtDisplayTextLine(3, "Red:    %d",  red);
	nxtDisplayTextLine(4, "Green:  %d",  green);
	nxtDisplayTextLine(5, "Blue:   %d",  blue);

  while (green > 150||green < 100)
  {
  	motor[lift]=-255;
  	getRGB(failSafe, red, green, blue);
  	wait10Msec(1);
  }
  	motor[lift]=0;
}
